import React, { useEffect, useState } from 'react';
import { api } from '../services/api.ts';
export function AdminTermsPanel() {
  const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authorized,setAuthorized]=useState(false),[selected,setSelected]=useState<any>(null);
  const [offset,setOffset]=useState(0),[nextOffset,setNextOffset]=useState<number|null>(null),[publicConsent,setPublicConsent]=useState(false);
  const load=async()=>{try{const session=await api.auth.me();if(!session.authenticated||session.user.role!=='admin'){setAuthorized(false);setRows([]);return;}const res=await api.terms.adminEvidence(offset,publicConsent);setRows(res.data);setNextOffset(res.nextOffset);setAuthorized(true);setError('');}catch(err:any){setRows([]);setError(err.message);}};
  useEffect(()=>{load();},[offset,publicConsent]);
  return <section className="bg-white rounded-[6px] border border-[#e1e7e4] p-6 space-y-5 text-xs text-[#123540]"><h2 className="text-lg font-bold">Versioned Terms Acceptance Evidence</h2>{error&&<p role="alert" className="text-red-700">{error}</p>}
    {!authorized?<form className="space-y-4 max-w-md" onSubmit={async e=>{e.preventDefault();try{const res=await api.auth.login(email,password);if(res.user.role!=='admin'){await api.auth.logout();throw new Error('Active Admin account required.');}await load();}catch(err:any){setError(err.message);}}}><p>An authenticated active Admin account is required to inspect acceptance evidence.</p><label className="block">Admin email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} className="block border rounded p-2 w-full"/></label><label className="block">Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} className="block border rounded p-2 w-full"/></label><button className="bg-[#123f47] text-white rounded px-4 py-2">Sign In</button></form>:<><button onClick={load} className="underline">Refresh Evidence</button><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr>{['Company','User','Role / Type','Version','Accepted At','Status','Content'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.acceptance_id} className="border-t border-[#e1e7e4]"><td className="p-3">{row.company}</td><td className="p-3">{row.email}</td><td className="p-3">{row.role} / {row.terms_type}</td><td className="p-3">{row.terms_version}</td><td className="p-3">{row.accepted_at}</td><td className="p-3">{row.acceptance_status}</td><td className="p-3"><button className="underline" onClick={()=>setSelected(row)}>Inspect Accepted Version</button></td></tr>)}</tbody></table>{rows.length===0&&<p>No acceptance evidence has been recorded.</p>}</div></>}
    {selected&&<section className="border rounded p-4 space-y-3"><button onClick={()=>setSelected(null)} className="underline">Close Version</button><h3 className="font-bold">{selected.title} — {selected.terms_version}</h3><p className="break-all">SHA-256: {selected.content_sha256}</p><p>Acceptance: {selected.acceptance_id} · Audit: {selected.audit_reference}</p><pre className="whitespace-pre-wrap font-['DM_Sans'] leading-relaxed">{selected.content_text}</pre></section>}
    {authorized&&<div className="flex flex-wrap gap-4"><button className="underline" onClick={()=>{setOffset(0);setSelected(null);setPublicConsent(!publicConsent);}}>{publicConsent?'View Organization Terms':'View Get a Quote Consent'}</button><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-200))}>Previous</button><button disabled={nextOffset===null} onClick={()=>{if(nextOffset!==null)setOffset(nextOffset);}}>Next</button></div>}
  </section>;
}
