import type {Env} from './index.ts';
export async function publicDiscoveryRoute(request:Request,env:Env):Promise<Response|null>{
 if(request.method!=='GET'||new URL(request.url).pathname!=='/api/public/discovery')return null;
 const rfqs=await env.DB.prepare(`SELECT r.id,r.reference_code,r.title,r.category,r.location_emirate,r.submission_deadline,c.company_name,c.contact_person,c.contact_phone,c.trade_license_number,c.address,u.email FROM rfqs r JOIN contractors c ON c.id=r.contractor_id JOIN users u ON u.id=c.user_id WHERE u.status='active' AND r.deleted_at IS NULL AND r.status IN ('reviewed_published','receiving_quotations') AND r.submission_deadline>? ORDER BY r.published_at DESC LIMIT 12`).bind(new Date().toISOString()).all<any>();
 const contractors=await env.DB.prepare(`SELECT c.company_name,c.emirate FROM contractors c JOIN users u ON u.id=c.user_id WHERE u.status='active' AND c.verified_at IS NOT NULL AND c.directory_visible=1 ORDER BY c.company_name LIMIT 100`).all<any>();
 const vendors=await env.DB.prepare(`SELECT v.company_name,v.trade_categories,v.emirates_serviced FROM vendors v JOIN users u ON u.id=v.user_id WHERE u.status='active' AND v.verification_status='verified' AND v.directory_visible=1 ORDER BY v.company_name LIMIT 100`).all<any>();
 const statistics=await env.DB.prepare(`SELECT
 (SELECT count(*) FROM contractors c JOIN users u ON u.id=c.user_id WHERE c.verified_at IS NOT NULL AND u.status='active') AS verifiedContractors,
 (SELECT count(*) FROM vendors v JOIN users u ON u.id=v.user_id WHERE v.verification_status='verified' AND u.status='active') AS verifiedVendors,
 (SELECT count(*) FROM rfqs r JOIN contractors c ON c.id=r.contractor_id JOIN users u ON u.id=c.user_id WHERE u.status='active' AND r.deleted_at IS NULL AND r.status NOT IN ('draft','cancelled')) AS projects,
 (SELECT count(*) FROM rfqs r JOIN contractors c ON c.id=r.contractor_id JOIN users u ON u.id=c.user_id WHERE u.status='active' AND r.deleted_at IS NULL AND r.status IN ('reviewed_published','receiving_quotations') AND r.submission_deadline>?) AS openRfqs,
 (SELECT count(*) FROM awards a JOIN contractors c ON c.id=a.contractor_id JOIN users u ON u.id=c.user_id WHERE u.status='active') AS awardedRfqs`).bind(new Date().toISOString()).first();
 return Response.json({success:true,data:{statistics,rfqs:rfqs.results.map(r=>({referenceCode:r.reference_code,title:r.category+' procurement — '+r.location_emirate,category:r.category,emirate:r.location_emirate,submissionDeadline:r.submission_deadline})),contractors:contractors.results.map(c=>({companyName:c.company_name,emirate:c.emirate})),vendors:vendors.results.map(v=>({companyName:v.company_name,categories:JSON.parse(v.trade_categories),emirates:JSON.parse(v.emirates_serviced)}))}},{headers:{'Cache-Control':'no-store'}});
}
